- name: Install dependencies
  apt:
    name:
      - python3
      - python3-venv
      - python3-pip
      - git
    update_cache: yes

- name: Clone repository
  git:
    repo: 'https://github.com/andrej-oss/weather-bot.git'
    dest: /home/ubuntu/weather-bot
    version: main
    force: yes

- name: Create virtualenv
  command: python3 -m venv /home/ubuntu/weather-bot/.venv
  args:
    creates: /home/ubuntu/weather-bot/.venv

- name: Install python packages
  pip:
    requirements: /home/ubuntu/weather-bot/requirements.txt
    virtualenv: /home/ubuntu/weather-bot/.venv

- name: Upload systemd service
  template:
    src: weatherbot.service.j2
    dest: /etc/systemd/system/weatherbot.service
    mode: '0644'

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable and start bot service
  systemd:
    name: weatherbot
    state: started
    enabled: yes
